name: Devpass checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        run: sudo apt-get install ruby

      - name: Download test file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/devpass-community/challenge-1698858661375/test.rb -o test.rb

      - name: Run unit tests
        run: ruby test.rb
